// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfePxA5I9jXe162QppdNZdg6UeJfhzGY8',
    appId: '1:617355588383:web:83a4ae648c1ed9b0a9762a',
    messagingSenderId: '617355588383',
    projectId: 'cf-romance',
    authDomain: 'cf-romance.firebaseapp.com',
    storageBucket: 'cf-romance.appspot.com',
    measurementId: 'G-1H6QP39FW3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrAUQ7-5K0xQ_KiYOkc1pgdXGTesJbhuU',
    appId: '1:617355588383:android:a5ff94b4b534b174a9762a',
    messagingSenderId: '617355588383',
    projectId: 'cf-romance',
    storageBucket: 'cf-romance.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhfFktz43kLmbgHIEAfAE81iBew9qckGY',
    appId: '1:617355588383:ios:5a825293df6fbf9ba9762a',
    messagingSenderId: '617355588383',
    projectId: 'cf-romance',
    storageBucket: 'cf-romance.appspot.com',
    iosBundleId: 'com.example.childfreeRomance',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhfFktz43kLmbgHIEAfAE81iBew9qckGY',
    appId: '1:617355588383:ios:a817ae2a622e4628a9762a',
    messagingSenderId: '617355588383',
    projectId: 'cf-romance',
    storageBucket: 'cf-romance.appspot.com',
    iosBundleId: 'com.example.childfreeRomance.RunnerTests',
  );
}
