// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEbC0AP3_2TfARQuWs5EbFfOzUxMHjQvE',
    appId: '1:1020911922465:web:5012ae03df58f8e7ef2260',
    messagingSenderId: '1020911922465',
    projectId: 'childfree-connection',
    authDomain: 'childfree-connection.firebaseapp.com',
    storageBucket: 'childfree-connection.appspot.com',
    measurementId: 'G-QHJQSS0M85',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-vye-yfIthjJ91iu8HkXJGFkLbIeY0oA',
    appId: '1:1020911922465:android:dadd488cd1c30e03ef2260',
    messagingSenderId: '1020911922465',
    projectId: 'childfree-connection',
    storageBucket: 'childfree-connection.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3R1yErjihKYTCA8QQODpJGXp5FKlmoYE',
    appId: '1:1020911922465:ios:2a7446d04771702fef2260',
    messagingSenderId: '1020911922465',
    projectId: 'childfree-connection',
    storageBucket: 'childfree-connection.appspot.com',
    iosBundleId: 'com.example.childfreeRomance',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3R1yErjihKYTCA8QQODpJGXp5FKlmoYE',
    appId: '1:1020911922465:ios:e74661633cdc65beef2260',
    messagingSenderId: '1020911922465',
    projectId: 'childfree-connection',
    storageBucket: 'childfree-connection.appspot.com',
    iosBundleId: 'com.example.childfreeRomance.RunnerTests',
  );
}
