List<String> interests = [
  'Acting',
  'Animals',
  'Archery',
  'Art',
  'Astrology',
  'Astronomy',
  'Baking',
  'Beekeeping',
  'Birdwatching',
  'Board Games',
  'Camping',
  'Calligraphy',
  'Cartooning',
  'Caving',
  'Chess',
  'Coding',
  'Collecting',
  'Comic Books',
  'Concerts',
  'Cooking',
  'Crocheting',
  'Dancing',
  'DIY Projects',
  'Digital Art',
  'Diving',
  'Drone Flying',
  'Embroidery',
  'Extreme Sports',
  'Falconry',
  'Fashion',
  'Fashion Design',
  'Fishing',
  'Fitness',
  'Fire Dancing',
  'Gardening',
  'Genealogy',
  'Geocaching',
  'Glassblowing',
  'Graffiti Art',
  'Graphic Design',
  'Hiking',
  'History',
  'Horseback Riding',
  'Ice Skating',
  'Instrument Making',
  'Interior Design',
  'Jewelry Making',
  'Journaling',
  'Kite Flying',
  'Knitting',
  'LARPing',
  'Languages',
  'Lego Building',
  'Magic Tricks',
  'Makeup Artistry',
  'Marathons',
  'Martial Arts',
  'Metalworking',
  'Meditation',
  'Model Building',
  'Motocross',
  'Movies',
  'Music',
  'Origami',
  'Paintball',
  'Painting',
  'Paragliding',
  'Paranormal Investigation',
  'Photography',
  'Podcasting',
  'Pottery',
  'Puzzles',
  'Quilting',
  'Rappelling',
  'Reading',
  'Rock Climbing',
  'Rowing',
  'Running',
  'Sculpting',
  'Science',
  'Scuba Diving',
  'Self-Care',
  'Singing',
  'Skiing',
  'Skydiving',
  'Snowboarding',
  'Sports',
  'Stand-up Comedy',
  'Surfing',
  'Tattooing',
  'Technology',
  'Theater',
  'Trampolining',
  'Travel',
  'Urban Exploration',
  'Video Games',
  'Vintage Cars',
  'Virtual Reality Gaming',
  'Volunteering',
  'Wine Tasting',
  'Woodworking',
  'Writing',
  'Yoga',
];
